image: golang:1.21

variables:
  GITHUB_REPO: "git@github.com:migsc/cmdeagle.git"

stages:
- test
- mirror

test:
  stage: test
  script:
  - go mod download
  - go test ./...
  - go build ./...

mirror-to-github:
  stage: mirror
  image: alpine:latest
  variables:
    GIT_STRATEGY: clone
  before_script:
  - apk add --no-cache git openssh-client
  - eval $(ssh-agent -s)
  - echo "${GITHUB_SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "${GITLAB_USER_EMAIL}"
  - git config --global user.name "${GITLAB_USER_NAME}"
  script:
  # Create a new temporary directory for the GitHub repo
  - mkdir -p /tmp/github
  - cd /tmp/github
  # Clone the GitHub repository (create new if doesn't exist)
  - git clone $GITHUB_REPO . || git init
  - git remote add origin $GITHUB_REPO || git remote set-url origin $GITHUB_REPO
  # Copy only the cmdeagle package contents
  - rm -rf *
  - cp -r $CI_PROJECT_DIR/packages/cmdeagle/* .
  # Push to GitHub
  - git add .
  - git commit -m "Sync from GitLab - ${CI_COMMIT_SHA}" || echo "No changes to commit"
  - git push -u origin HEAD:main --force
  only:
  - main
  - master
